apiVersion: v1
kind: Secret
metadata:
  name: s3-migration-secrets
  namespace: s3-migration
  labels:
    app: s3-migration
type: Opaque
data:
  # Base64 encoded encryption key (32 bytes recommended)
  # Generate with: openssl rand -base64 32 | tr -d '\n' | base64
  # Or leave empty to auto-generate
  encryption-key: ""
  
---
# Example: Secret for private GitLab registry (if needed)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gitlab-registry-secret
#   namespace: default
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: <base64-encoded-docker-config>
# 
# To create this secret, use:
# kubectl create secret docker-registry gitlab-registry-secret \
#   --docker-server=registry.gitlab.com \
#   --docker-username=<your-username> \
#   --docker-password=<your-token> \
#   --docker-email=<your-email>

